// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: messages/OpenApiMessages.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoOAApplicationAuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayloadType  *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=messages.ProtoOAPayloadType,def=2100" json:"payloadType,omitempty"`
	ClientId     *string             `protobuf:"bytes,2,req,name=clientId" json:"clientId,omitempty"`         //The unique Client ID provided during the registration.
	ClientSecret *string             `protobuf:"bytes,3,req,name=clientSecret" json:"clientSecret,omitempty"` //The unique Client Secret provided during the registration
}

// Default values for ProtoOAApplicationAuthReq fields.
const (
	Default_ProtoOAApplicationAuthReq_PayloadType = ProtoOAPayloadType_PROTO_OA_APPLICATION_AUTH_REQ
)

func (x *ProtoOAApplicationAuthReq) Reset() {
	*x = ProtoOAApplicationAuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_OpenApiMessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoOAApplicationAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoOAApplicationAuthReq) ProtoMessage() {}

func (x *ProtoOAApplicationAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_OpenApiMessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoOAApplicationAuthReq.ProtoReflect.Descriptor instead.
func (*ProtoOAApplicationAuthReq) Descriptor() ([]byte, []int) {
	return file_messages_OpenApiMessages_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoOAApplicationAuthReq) GetPayloadType() ProtoOAPayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return Default_ProtoOAApplicationAuthReq_PayloadType
}

func (x *ProtoOAApplicationAuthReq) GetClientId() string {
	if x != nil && x.ClientId != nil {
		return *x.ClientId
	}
	return ""
}

func (x *ProtoOAApplicationAuthReq) GetClientSecret() string {
	if x != nil && x.ClientSecret != nil {
		return *x.ClientSecret
	}
	return ""
}

// * Response to the ProtoOAApplicationAuthReq request.
type ProtoOAApplicationAuthRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayloadType *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=messages.ProtoOAPayloadType,def=2101" json:"payloadType,omitempty"`
}

// Default values for ProtoOAApplicationAuthRes fields.
const (
	Default_ProtoOAApplicationAuthRes_PayloadType = ProtoOAPayloadType_PROTO_OA_APPLICATION_AUTH_RES
)

func (x *ProtoOAApplicationAuthRes) Reset() {
	*x = ProtoOAApplicationAuthRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_OpenApiMessages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoOAApplicationAuthRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoOAApplicationAuthRes) ProtoMessage() {}

func (x *ProtoOAApplicationAuthRes) ProtoReflect() protoreflect.Message {
	mi := &file_messages_OpenApiMessages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoOAApplicationAuthRes.ProtoReflect.Descriptor instead.
func (*ProtoOAApplicationAuthRes) Descriptor() ([]byte, []int) {
	return file_messages_OpenApiMessages_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoOAApplicationAuthRes) GetPayloadType() ProtoOAPayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return Default_ProtoOAApplicationAuthRes_PayloadType
}

// * Request for getting Trader's deals historical data (execution details).
type ProtoOADealListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayloadType         *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=messages.ProtoOAPayloadType,def=2133" json:"payloadType,omitempty"`
	CtidTraderAccountId *int64              `protobuf:"varint,2,req,name=ctidTraderAccountId" json:"ctidTraderAccountId,omitempty"` // Unique identifier of the trader's account. Used to match responses to trader's accounts.
	FromTimestamp       *int64              `protobuf:"varint,3,req,name=fromTimestamp" json:"fromTimestamp,omitempty"`             // The UNIX time from which the search starts >=0 (1-1-1970). Validation: toTimestamp - fromTimestamp <= 604800000 (1 week).
	ToTimestamp         *int64              `protobuf:"varint,4,req,name=toTimestamp" json:"toTimestamp,omitempty"`                 // The UNIX time where to stop searching <= 2147483646000 (19-1-2038).
	MaxRows             *int32              `protobuf:"varint,5,opt,name=maxRows" json:"maxRows,omitempty"`                         // The maximum number of the deals to return.
}

// Default values for ProtoOADealListReq fields.
const (
	Default_ProtoOADealListReq_PayloadType = ProtoOAPayloadType_PROTO_OA_DEAL_LIST_REQ
)

func (x *ProtoOADealListReq) Reset() {
	*x = ProtoOADealListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_OpenApiMessages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoOADealListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoOADealListReq) ProtoMessage() {}

func (x *ProtoOADealListReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_OpenApiMessages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoOADealListReq.ProtoReflect.Descriptor instead.
func (*ProtoOADealListReq) Descriptor() ([]byte, []int) {
	return file_messages_OpenApiMessages_proto_rawDescGZIP(), []int{2}
}

func (x *ProtoOADealListReq) GetPayloadType() ProtoOAPayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return Default_ProtoOADealListReq_PayloadType
}

func (x *ProtoOADealListReq) GetCtidTraderAccountId() int64 {
	if x != nil && x.CtidTraderAccountId != nil {
		return *x.CtidTraderAccountId
	}
	return 0
}

func (x *ProtoOADealListReq) GetFromTimestamp() int64 {
	if x != nil && x.FromTimestamp != nil {
		return *x.FromTimestamp
	}
	return 0
}

func (x *ProtoOADealListReq) GetToTimestamp() int64 {
	if x != nil && x.ToTimestamp != nil {
		return *x.ToTimestamp
	}
	return 0
}

func (x *ProtoOADealListReq) GetMaxRows() int32 {
	if x != nil && x.MaxRows != nil {
		return *x.MaxRows
	}
	return 0
}

// * Generic response when an ERROR occurred.
type ProtoOAErrorRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayloadType             *ProtoOAPayloadType `protobuf:"varint,1,opt,name=payloadType,enum=messages.ProtoOAPayloadType,def=2142" json:"payloadType,omitempty"`
	CtidTraderAccountId     *int64              `protobuf:"varint,2,opt,name=ctidTraderAccountId" json:"ctidTraderAccountId,omitempty"`         //The unique identifier of the trader's account in cTrader platform.
	ErrorCode               *string             `protobuf:"bytes,3,req,name=errorCode" json:"errorCode,omitempty"`                              // The name of the ProtoErrorCode or the other custom ErrorCodes (e.g. ProtoCHErrorCode).
	Description             *string             `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`                          // The error description.
	MaintenanceEndTimestamp *int64              `protobuf:"varint,5,opt,name=maintenanceEndTimestamp" json:"maintenanceEndTimestamp,omitempty"` // The timestamp in seconds when the current maintenance session will be ended.
}

// Default values for ProtoOAErrorRes fields.
const (
	Default_ProtoOAErrorRes_PayloadType = ProtoOAPayloadType_PROTO_OA_ERROR_RES
)

func (x *ProtoOAErrorRes) Reset() {
	*x = ProtoOAErrorRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_OpenApiMessages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProtoOAErrorRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoOAErrorRes) ProtoMessage() {}

func (x *ProtoOAErrorRes) ProtoReflect() protoreflect.Message {
	mi := &file_messages_OpenApiMessages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoOAErrorRes.ProtoReflect.Descriptor instead.
func (*ProtoOAErrorRes) Descriptor() ([]byte, []int) {
	return file_messages_OpenApiMessages_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoOAErrorRes) GetPayloadType() ProtoOAPayloadType {
	if x != nil && x.PayloadType != nil {
		return *x.PayloadType
	}
	return Default_ProtoOAErrorRes_PayloadType
}

func (x *ProtoOAErrorRes) GetCtidTraderAccountId() int64 {
	if x != nil && x.CtidTraderAccountId != nil {
		return *x.CtidTraderAccountId
	}
	return 0
}

func (x *ProtoOAErrorRes) GetErrorCode() string {
	if x != nil && x.ErrorCode != nil {
		return *x.ErrorCode
	}
	return ""
}

func (x *ProtoOAErrorRes) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProtoOAErrorRes) GetMaintenanceEndTimestamp() int64 {
	if x != nil && x.MaintenanceEndTimestamp != nil {
		return *x.MaintenanceEndTimestamp
	}
	return 0
}

var File_messages_OpenApiMessages_proto protoreflect.FileDescriptor

var file_messages_OpenApiMessages_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x4f, 0x70, 0x65, 0x6e, 0x41,
	0x70, 0x69, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x23, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2f, 0x4f, 0x70, 0x65, 0x6e, 0x41, 0x70, 0x69, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xba, 0x01, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4f, 0x41, 0x41, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x5d, 0x0a,
	0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x4f, 0x41, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x3a, 0x1d, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x4f, 0x41, 0x5f, 0x41, 0x50, 0x50, 0x4c, 0x49,
	0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x52, 0x45, 0x51, 0x52,
	0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x22, 0x7a, 0x0a, 0x19,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4f, 0x41, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x12, 0x5d, 0x0a, 0x0b, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4f,
	0x41, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x1d, 0x50, 0x52,
	0x4f, 0x54, 0x4f, 0x5f, 0x4f, 0x41, 0x5f, 0x41, 0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x52, 0x45, 0x53, 0x52, 0x0b, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x22, 0x80, 0x02, 0x0a, 0x12, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x4f, 0x41, 0x44, 0x65, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12,
	0x56, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4f, 0x41, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x3a, 0x16, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x4f, 0x41, 0x5f, 0x44, 0x45, 0x41,
	0x4c, 0x5f, 0x4c, 0x49, 0x53, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x63, 0x74, 0x69, 0x64, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x13, 0x63, 0x74, 0x69, 0x64, 0x54, 0x72, 0x61, 0x64, 0x65, 0x72,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x66, 0x72, 0x6f,
	0x6d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x02, 0x28, 0x03,
	0x52, 0x0d, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x04,
	0x20, 0x02, 0x28, 0x03, 0x52, 0x0b, 0x74, 0x6f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x52, 0x6f, 0x77, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x52, 0x6f, 0x77, 0x73, 0x22, 0x91, 0x02, 0x0a, 0x0f,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4f, 0x41, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x12,
	0x52, 0x0a, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x4f, 0x41, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x3a, 0x12, 0x50, 0x52, 0x4f, 0x54, 0x4f, 0x5f, 0x4f, 0x41, 0x5f, 0x45, 0x52, 0x52,
	0x4f, 0x52, 0x5f, 0x52, 0x45, 0x53, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x30, 0x0a, 0x13, 0x63, 0x74, 0x69, 0x64, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x13, 0x63, 0x74, 0x69, 0x64, 0x54, 0x72, 0x61, 0x64, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x17, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x17, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61,
	0x6e, 0x63, 0x65, 0x45, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x42,
	0x21, 0x5a, 0x1f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x61,
	0x72, 0x6c, 0x6f, 0x73, 0x6f, 0x6b, 0x75, 0x6d, 0x75, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73,
}

var (
	file_messages_OpenApiMessages_proto_rawDescOnce sync.Once
	file_messages_OpenApiMessages_proto_rawDescData = file_messages_OpenApiMessages_proto_rawDesc
)

func file_messages_OpenApiMessages_proto_rawDescGZIP() []byte {
	file_messages_OpenApiMessages_proto_rawDescOnce.Do(func() {
		file_messages_OpenApiMessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_OpenApiMessages_proto_rawDescData)
	})
	return file_messages_OpenApiMessages_proto_rawDescData
}

var file_messages_OpenApiMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_messages_OpenApiMessages_proto_goTypes = []interface{}{
	(*ProtoOAApplicationAuthReq)(nil), // 0: messages.ProtoOAApplicationAuthReq
	(*ProtoOAApplicationAuthRes)(nil), // 1: messages.ProtoOAApplicationAuthRes
	(*ProtoOADealListReq)(nil),        // 2: messages.ProtoOADealListReq
	(*ProtoOAErrorRes)(nil),           // 3: messages.ProtoOAErrorRes
	(ProtoOAPayloadType)(0),           // 4: messages.ProtoOAPayloadType
}
var file_messages_OpenApiMessages_proto_depIdxs = []int32{
	4, // 0: messages.ProtoOAApplicationAuthReq.payloadType:type_name -> messages.ProtoOAPayloadType
	4, // 1: messages.ProtoOAApplicationAuthRes.payloadType:type_name -> messages.ProtoOAPayloadType
	4, // 2: messages.ProtoOADealListReq.payloadType:type_name -> messages.ProtoOAPayloadType
	4, // 3: messages.ProtoOAErrorRes.payloadType:type_name -> messages.ProtoOAPayloadType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_messages_OpenApiMessages_proto_init() }
func file_messages_OpenApiMessages_proto_init() {
	if File_messages_OpenApiMessages_proto != nil {
		return
	}
	file_messages_OpenApiModelMessages_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_messages_OpenApiMessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoOAApplicationAuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_OpenApiMessages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoOAApplicationAuthRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_OpenApiMessages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoOADealListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_OpenApiMessages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProtoOAErrorRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_OpenApiMessages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_OpenApiMessages_proto_goTypes,
		DependencyIndexes: file_messages_OpenApiMessages_proto_depIdxs,
		MessageInfos:      file_messages_OpenApiMessages_proto_msgTypes,
	}.Build()
	File_messages_OpenApiMessages_proto = out.File
	file_messages_OpenApiMessages_proto_rawDesc = nil
	file_messages_OpenApiMessages_proto_goTypes = nil
	file_messages_OpenApiMessages_proto_depIdxs = nil
}
